package org.springframework.ntfh.cardEfects;

public enum CardNameEnumerate {
    COMPANYERO_LOBO, DISPARO_CERTERO, DISPARO_RAPIDO, EN_LA_DIANA, LLUVIA_DE_FLECHAS, RECOGER_FLECHAS, SUPERVIVIENCIA, //Ranger cards
    ATAQUE_BRUTAL, CARGA_CON_ESCUDO, DOBLE_ESPADAZO, ESCUDO, ESPADAZAO, PASO_ATRAS, TODO_O_NADA, VOZ_DE_ALIENTO, //Paladin cards
    AURA_PROTECTORA, BOLA_DE_FUEGO, DISPARO_GELIDO, FLECHA_CORROSIVA, GOLPE_DE_BASTON, ORBE_CURATIVO,PROYECTIL_IGNEO, RECONSTITUCION, TORRENTE_DE_LUZ, //Wizard cards 
    AL_CORAZON, ATAQUE_FURTIVO, BALLESTA_PRECISA, EN_LAS_SOMBRAS, ENGANYAR, ROBAR_BOLSILLOS, SAQUEO_1, SAQUEO_2, TRAMPA, // Rogue cards
    DAGA_ELFICA, POCION_CURATIVA, PIEDRA_DE_AMOLAR, VIAL_DE_CONJURACION, ELIXIR_DE_CONCENTRACION, CAPA_ELFICA, ARAMADURA_DE_PLACAS, ALABRADA_ORCA, ARCO_COMPUESTO //Market cards 
}
