package org.springframework.ntfh.entity.scene;

public enum SceneTypeEnum {
    MERCADO_DE_LOTHARION, CAMPO_DE_BATALLA, LAGRIMAS_DE_ARADIEL, LODAZAL_DE_KALERN, MONTANAS_DE_UR, PANTANO_UMBRIO,
    PLANICIE_DE_SKAARG, PORTAL_DE_ULTHAR, PUERTO_DE_EQUE, RUINAS_DE_BRUNMAR, YACIMIENTOS_DE_JADE, YERMO_DE_CEMENMAR
}
