export const HOME = "/";
export const LOGIN = "/login";
export const SIGNUP = "/signup";
export const PROFILE = "/profile/:username";
export const EDIT_PROFILE = "/profile/:username/edit";
export const EDIT_ACHIEVEMENT = "/achievements/:achievementId/edit";
export const CREATE_LOBBY = "/lobbies/new"; // POST
export const BROWSE_LOBBIES = "/lobbies"; // GET
export const GAME = "/games/:gameId";
export const LOBBY = "/lobbies/:lobbyId";
export const NOT_FOUND = "/not-found";
export const ADMIN_PAGE = "/admin";
export const STATISTICS = "/statistics";
export const ACHIEVEMENTS = "/achievements";
