package org.springframework.ntfh.entity.playablecard.abilitycard;

public enum AbilityCardTypeEnum {
    // Warrior
    ATAQUE_BRUTAL, CARGA_CON_ESCUDO, DOBLE_ESPADAZO, ESCUDO, ESPADAZO, PASO_ATRAS, TODO_O_NADA, VOZ_DE_ALIENTO,

    // Ranger
    COMPANERO_LOBO, DISPARO_CERTERO, DISPARO_RAPIDO, EN_LA_DIANA, LLUVIA_DE_FLECHAS, RECOGER_FLECHAS, SUPERVIVENCIA,

    // Rogue
    AL_CORAZON, ATAQUE_FURTIVO, BALLESTA_PRECISA, EN_LAS_SOMBRAS, ENGANAR, ROBAR_BOLSILLOS, SAQUEO, TRAMPA,

    // Wizard
    AURA_PROTECTORA, BOLA_DE_FUEGO, DISPARO_GELIDO, FLECHA_CORROSIVA, GOLPE_DE_BASTON, ORBE_CURATIVO, PROYECTIL_IGNEO,
    RECONSTITUCION, TORRENTE_DE_LUZ,

    // Market (They become AbilityCardIngame entities when purchased)
    DAGA_ELFICA, POCION_CURATIVA, PIEDRA_DE_AMOLAR, VIAL_DE_CONJURACION, ELIXIR_DE_CONCENTRACION, CAPA_ELFICA,
    ARMADURA_DE_PLACAS, ALABARDA_ORCA, ARCO_COMPUESTO
}
